services:
  db:
    container_name: db
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    networks:
      - cachorrinho_network
    environment:
      POSTGRES_DB: cachorrinhodb
      POSTGRES_USER: salvacao 
      POSTGRES_PASSWORD: salvacao123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  web:
    container_name: web
    build: .
    command: sh -c "npx prisma migrate deploy && yarn dev"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3344:3344"
    environment:
      DATABASE_URL: postgresql://salvacao:salvacao123@db:5432/cachorrinhodb
      NODE_ENV: development
    networks:
      - cachorrinho_network
    
volumes:
  postgres_data:

networks:
  cachorrinho_network:
    driver: bridge
